# This is a basic workflow to help you get started with Actions
- name: Generate Plantuml
  # You may pin to the exact commit or the version.
  # uses: grassedge/generate-plantuml-action@4936762686b831393728392054322cfde20645e8
  uses: grassedge/generate-plantuml-action@v1.5
  with:
    # path to directory which generated svg is stored
    path: # optional, default is .
    # the commit message when committing generated images
    message: # optional, default is Render PlantUML files
